In [1]:
import numpy as np

In [2]:
#!pip install numpy

In [3]:
# https://jalammar.github.io/visual-numpy/

In [4]:
my_list  = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [10]:
my_numpy_array.max() # it is benefical for mathematical operations 

np.int64(40)

In [15]:
# we can use ones and zeros for matrixes

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.random.random(5) #  to create random numbers between 0 and 1

array([0.84838426, 0.34868543, 0.82883933, 0.50981609, 0.63355418])

In [16]:
# array arithmetic

In [18]:
my_list1 = [1,2]

In [19]:
my_list2 = [2,3]

In [26]:
my_list1 + my_list2 # it concatenates lists 

[1, 2, 2, 3]

In [22]:
my_numpy_array1 = np.array(my_list1)

In [23]:
my_numpy_array2 = np.array(my_list2)

In [25]:
my_numpy_array1 + my_numpy_array2 # this one adds numpy arrays

array([3, 5])

In [27]:
# we can use numpy arrays to make mathematical operations without loops

In [28]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [29]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [30]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [31]:
my_numpy_array1*5

array([ 5, 10])

In [32]:
my_list1 *5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [33]:
other_array = np.array ([10,20,30,40,50])

In [34]:
other_array.min()

np.int64(10)

In [35]:
other_array.sum()

np.int64(150)

In [36]:
my_numpy_array1

array([1, 2])

In [37]:
other_array

array([10, 20, 30, 40, 50])

In [40]:
# my_numpy_array1 + other_array we can't they don't have sama number of elements

In [41]:
# Broadcasting describes how Numpy treats arrays with different shapes during arithemtic operations.

In [43]:
#Indexing and arange function

In [44]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np_array = np.arange(0,10)

In [48]:
np_array[0]

np.int64(0)

In [49]:
np_array[-1]

np.int64(9)

In [50]:
np_array[1:4:]

array([1, 2, 3])

In [51]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
np_array[2:6:2] # start from 2. index stop at 6. index and step size is 2

array([2, 4])

In [53]:
# random

In [54]:
np.random.randn(4)

array([-0.03985548, -1.6289318 , -0.63694171,  0.51873113])

In [55]:
# to obtain matrix
np.random.randn(4,4)

array([[-1.67691295,  0.74224575,  0.80671196,  1.48025009],
       [ 0.42718401,  0.49769053,  0.53975263, -0.68465179],
       [-0.88338416, -0.80397533, -1.02727662,  2.20304065],
       [ 0.68879083,  0.43087171, -0.56419495, -1.19778032]])

In [56]:
np.random.randint(1,300,5) # gives five integers randomly between 1 and 300

array([ 77, 115, 192, 255,  20], dtype=int32)