In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][0]

5

In [6]:
# row * column

In [7]:
numpy_matrix = np.array([[5,10],[15,20]])

In [9]:
numpy_matrix # it gives in the shape of matrix

array([[ 5, 10],
       [15, 20]])

In [10]:
numpy_matrix.sum()

np.int64(50)

In [11]:
np.ones(3)

array([1., 1., 1.])

In [13]:
#np.ones(3,3) this one is wrong

In [15]:
np.ones((3,3)) # to create a matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.random.random((3,2))

array([[0.07399955, 0.35622441],
       [0.87852334, 0.42650572],
       [0.83452543, 0.57914397]])

In [19]:
# matrix artihmetic

In [29]:
first_array = np.array([[10,20],[30,40]])

In [28]:
second_array = np.array([[5,15],[25,35]])

In [30]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [31]:
first_array

array([[10, 20],
       [30, 40]])

In [36]:
third_array = np.array ([[50,60]])

In [37]:
third_array

array([[50, 60]])

In [38]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [39]:
fourth_array = np.array([[10,20,30,40,50]])

In [41]:
# first_array + fourth_array due to broadcasting dispute

In [42]:
first_array *2

array([[20, 40],
       [60, 80]])

In [43]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [45]:
third_array = np.array([[10],[20]])

In [46]:
third_array

array([[10],
       [20]])

In [47]:
# to learn shape 
third_array.shape

(2, 1)

In [48]:
first_array.shape

(2, 2)

In [49]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [50]:
first_array

array([[10, 20],
       [30, 40]])

In [51]:
# matrix multiplication

In [52]:
first_array

array([[10, 20],
       [30, 40]])

In [53]:
second_array

array([[ 5, 15],
       [25, 35]])

In [55]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [56]:
# dot product

In [57]:
# we can product if they like anythingxn and nxanything

In [58]:
first_matrix = np.array([[10,20,30]])

In [59]:
first_matrix

array([[10, 20, 30]])

In [60]:
first_matrix.shape

(1, 3)

In [61]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [62]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [63]:
second_matrix.shape

(3, 2)

In [65]:
# first_matrix * second_matrix  we can use dat product to prevent eror

In [69]:
result_matrix = first_matrix.dot(second_matrix)

In [70]:
result_matrix.shape

(1, 2)