In [1]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20) # create 20 element between 1 and 20

In [9]:
new_array

array([42, 59, 25, 36, 74,  1, 97, 53, 29, 79, 52, 88, 83, 61, 45, 99, 53,
       60, 98, 98], dtype=int32)

In [10]:
new_array > 25

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [11]:
new_array[new_array > 25]

array([42, 59, 36, 74, 97, 53, 29, 79, 52, 88, 83, 61, 45, 99, 53, 60, 98,
       98], dtype=int32)

In [12]:
new_array[new_array < 25]

array([1], dtype=int32)

In [13]:
# transpose & reshape 

In [16]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [17]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [18]:
matrix_array.shape

(3, 2)

In [21]:
matrix_array.transpose() # changes rows and columns

array([[10, 20, 30],
       [20, 30, 40]])

In [26]:
matrix_array.T # to bring transposed version we can use T

array([[10, 20, 30],
       [20, 30, 40]])

In [31]:
random_array = np.random.random((6,1))


In [29]:
random_array

array([0.29519557, 0.65291219, 0.70745808, 0.35735877, 0.56820082,
       0.44129203])

In [32]:
random_array.reshape(3,2)

array([[0.20605903, 0.10373003],
       [0.74918959, 0.45703811],
       [0.92550428, 0.83950127]])

In [33]:
random_array.reshape(2,3)

array([[0.20605903, 0.10373003, 0.74918959],
       [0.45703811, 0.92550428, 0.83950127]])

In [34]:
random_array.shape

(6, 1)

In [35]:
#z-score

In [42]:
data = np.array([10,12,13,15,18,25,100,105])# 100 and 105 are outlier

In [39]:
#outlier

In [43]:
mean = np.mean(data)

In [44]:
mean 

np.float64(37.25)

In [45]:
data.sum()

np.int64(298)

In [46]:
std = np.std(data)

In [47]:
std

np.float64(37.9333296719389)

In [49]:
z_scores= (data - mean) / std

In [50]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [51]:
data[z_scores > 1]

array([100, 105])

In [52]:
# math equations

In [53]:
# 2x +3y = 8 and 5x + 7y = 19

In [54]:
#coefficient matrix

In [55]:
A = np.array([[2,3],[5,7]])

In [56]:
# constant

In [58]:
b = np.array([8,19])

In [59]:
solution = np.linalg.solve(A,b)

In [60]:
solution

array([1., 2.])